version: '2'

services:
  base:
    build:
      dockerfile: docker/Dockerfile
      context: ./
    image: dionysus/dionysus_api
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./env/default.env
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION

  dionysus:
    extends:
      service: base
    command: /bin/bash -c 'export STAGE=$${STAGE:-dev} && yarn run start'
    ports:
      - '3000:3000'
    container_name: dionysus_api
    links:
      - dynamo

  test:
    extends:
      service: base
    command: /bin/bash -c 'export STAGE=$${STAGE:-test} && yarn run test:run'
    container_name: test_api
    links:
      - dynamo
    environment:
      DYNAMODB_TABLE_PREFIX: "dionysus-test"

  dynamo:
    image: "cnadiminti/dynamodb-local"
    ports:
      - "8010:8010"
    environment:
      DYNAMODB_PORT: "8010"
