service:
  name: dionysus

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10

functions:
  graphql:
    handler: handler.graphqlHandler
    events:
      - http:
          method: get
          path: graphql
  graphql:
    handler: handler.graphqlHandler
    events:
      - http:
          method: post
          path: graphql
